# Generated by Django 4.0.3 on 2022-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_produit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('titre1', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='img/home')),
                ('titre2', models.TextField()),
                ('image2', models.ImageField(blank=True, null=True, upload_to='img/home')),
            ],
        ),
    ]
