# Generated by Django 4.0.3 on 2022-03-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
