# Generated by Django 4.0.3 on 2022-03-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
