# Generated by Django 4.0.3 on 2022-03-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_produit_description_alter_produit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='price',
            new_name='prix',
        ),
    ]
